// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwcdm-6YUI7JP7T7iBPS-3hdP-Q0cqJ4Y',
    appId: '1:344204788213:web:986a4a7295a7ead33920bc',
    messagingSenderId: '344204788213',
    projectId: 'e-commerce-ee285',
    authDomain: 'e-commerce-ee285.firebaseapp.com',
    storageBucket: 'e-commerce-ee285.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsSybul2M6RAE5ukNZsd2KD8Bd5x0idis',
    appId: '1:344204788213:android:1d6ce1e269a76e593920bc',
    messagingSenderId: '344204788213',
    projectId: 'e-commerce-ee285',
    storageBucket: 'e-commerce-ee285.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASB0A_1PI0blBtCy9xBkqBCfVewcsCdvI',
    appId: '1:344204788213:ios:312b377e55c5c8103920bc',
    messagingSenderId: '344204788213',
    projectId: 'e-commerce-ee285',
    storageBucket: 'e-commerce-ee285.appspot.com',
    iosClientId: '344204788213-fahf4e7qacr5ga6uatbq42cohgcde07b.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASB0A_1PI0blBtCy9xBkqBCfVewcsCdvI',
    appId: '1:344204788213:ios:9618e41ea84d91703920bc',
    messagingSenderId: '344204788213',
    projectId: 'e-commerce-ee285',
    storageBucket: 'e-commerce-ee285.appspot.com',
    iosClientId: '344204788213-e0c5s123cc0u5q1r513iverqiajhoprp.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
